/**
 * Do not edit directly
 * Generated on Wed, 20 Apr 2022 10:54:31 GMT
 */

export const colorApplicationPrimary = "#83cef5"; // The primary color is used to indicate primary actions, selected elements or as background color for app bars.
export const colorApplicationSecondary = "#fd90b1"; // The secondary color is used to indicate selection controls, floating actions or overline text.
export const colorApplicationTertiary = "#ce8dce"; // The tertiary color is used to colorize information graphics.
export const colorApplicationQuaternary = "#1b4e8e"; // The quaternary color is used to colorize information graphics or primary actions in snackbars.
export const colorApplicationBackground = "#13151b"; // The quaternary color is used to colorize information graphics or primary actions in snackbars.
export const colorApplicationSurface = "#13151b"; // The surface color is used as the background color for cards, text fields, sheets, dialogs, menus and chips.
export const colorApplicationError = "#f9a9ab"; // The error color is used for error text.
export const colorApplicationOutline = "#5d687f"; // The outline color is used for components with an outline like cards, text fields or buttons.
export const colorApplicationContrastPrimary = "#061a38"; // The primary contrast color is used for elements like text that is displayed on a background with the primary color.
export const colorApplicationContrastSecondary = "#061a38"; // The secondary contrast color is used for elements like text that is displayed on a background with the secondary color.
export const colorApplicationContrastTertiary = "#061a38"; // The tertiary contrast color is used for elements like text that is displayed on a background with the tertiary color.
export const colorApplicationContrastQuaternary = "#ffffff"; // The quaternary contrast color is used for elements like text that is displayed on a background with the quaternary color.
export const colorApplicationContrastBackground = "#ffffff"; // The background contrast color is used for elements like text that is displayed on a background with the background color.
export const colorApplicationContrastSurface = "#ffffff"; // The surface contrast color is used for elements like text that is displayed on a background with the surface color.
export const colorApplicationContrastError = "#061a38"; // The error contrast color is used for elements like text that is displayed on a background with the error color.
export const colorApplicationContrastOutline = "#061a38"; // The outline contrast color is used for elements like text that is displayed on a background with the outline color.
export const colorBrandNeutral50 = "#fafafa";
export const colorBrandNeutral100 = "#f5f5f5";
export const colorBrandNeutral200 = "#eeeeee";
export const colorBrandNeutral300 = "#e0e0e0";
export const colorBrandNeutral400 = "#bdbdbd";
export const colorBrandNeutral500 = "#a0a0a0";
export const colorBrandNeutral600 = "#757575";
export const colorBrandNeutral700 = "#555555";
export const colorBrandNeutral800 = "#424242";
export const colorBrandNeutral900 = "#212121";
export const colorBrandNeutralContrast50 = "#061a38";
export const colorBrandNeutralContrast100 = "#061a38";
export const colorBrandNeutralContrast200 = "#061a38";
export const colorBrandNeutralContrast300 = "#061a38";
export const colorBrandNeutralContrast400 = "#061a38";
export const colorBrandNeutralContrast500 = "#061a38";
export const colorBrandNeutralContrast600 = "#ffffff";
export const colorBrandNeutralContrast700 = "#ffffff";
export const colorBrandNeutralContrast800 = "#ffffff";
export const colorBrandNeutralContrast900 = "#ffffff";
export const colorBrandBlue50 = "#e1f4fd";
export const colorBrandBlue100 = "#b3e2f9";
export const colorBrandBlue200 = "#83cef5";
export const colorBrandBlue300 = "#56bbef";
export const colorBrandBlue400 = "#3aadec";
export const colorBrandBlue500 = "#2b9fe8";
export const colorBrandBlue600 = "#2892d9";
export const colorBrandBlue700 = "#257fc5";
export const colorBrandBlue800 = "#216eb1";
export const colorBrandBlue900 = "#1b4e8e";
export const colorBrandBlueContrast50 = "#061a38";
export const colorBrandBlueContrast100 = "#061a38";
export const colorBrandBlueContrast200 = "#061a38";
export const colorBrandBlueContrast300 = "#061a38";
export const colorBrandBlueContrast400 = "#061a38";
export const colorBrandBlueContrast500 = "#ffffff";
export const colorBrandBlueContrast600 = "#ffffff";
export const colorBrandBlueContrast700 = "#ffffff";
export const colorBrandBlueContrast800 = "#ffffff";
export const colorBrandBlueContrast900 = "#ffffff";
export const colorBrandDeepblue50 = "#e4e7ec";
export const colorBrandDeepblue100 = "#b9c3d1";
export const colorBrandDeepblue200 = "#8d9cb2";
export const colorBrandDeepblue300 = "#647694";
export const colorBrandDeepblue400 = "#445b80";
export const colorBrandDeepblue500 = "#20426e";
export const colorBrandDeepblue600 = "#1a3b66";
export const colorBrandDeepblue700 = "#11325c";
export const colorBrandDeepblue800 = "#0b2950";
export const colorBrandDeepblue900 = "#061a38";
export const colorBrandDeepblueContrast50 = "#061a38";
export const colorBrandDeepblueContrast100 = "#061a38";
export const colorBrandDeepblueContrast200 = "#061a38";
export const colorBrandDeepblueContrast300 = "#ffffff";
export const colorBrandDeepblueContrast400 = "#ffffff";
export const colorBrandDeepblueContrast500 = "#ffffff";
export const colorBrandDeepblueContrast600 = "#ffffff";
export const colorBrandDeepblueContrast700 = "#ffffff";
export const colorBrandDeepblueContrast800 = "#ffffff";
export const colorBrandDeepblueContrast900 = "#ffffff";
export const colorBrandGrayblue50 = "#edeef6";
export const colorBrandGrayblue100 = "#d0d6e2";
export const colorBrandGrayblue200 = "#b4baca";
export const colorBrandGrayblue300 = "#979fb3";
export const colorBrandGrayblue400 = "#818aa1";
export const colorBrandGrayblue500 = "#6c7690";
export const colorBrandGrayblue600 = "#5d687f";
export const colorBrandGrayblue700 = "#4c5568";
export const colorBrandGrayblue800 = "#292e3b";
export const colorBrandGrayblue900 = "#13151b";
export const colorBrandGrayblueContrast50 = "#061a38";
export const colorBrandGrayblueContrast100 = "#061a38";
export const colorBrandGrayblueContrast200 = "#061a38";
export const colorBrandGrayblueContrast300 = "#061a38";
export const colorBrandGrayblueContrast400 = "#ffffff";
export const colorBrandGrayblueContrast500 = "#ffffff";
export const colorBrandGrayblueContrast600 = "#ffffff";
export const colorBrandGrayblueContrast700 = "#ffffff";
export const colorBrandGrayblueContrast800 = "#ffffff";
export const colorBrandGrayblueContrast900 = "#ffffff";
export const colorBrandPink50 = "#ffe4ec";
export const colorBrandPink100 = "#febcd0";
export const colorBrandPink200 = "#fd90b1";
export const colorBrandPink300 = "#fc6191";
export const colorBrandPink400 = "#fa3c78";
export const colorBrandPink500 = "#f81060";
export const colorBrandPink600 = "#e70a5e";
export const colorBrandPink700 = "#d1045a";
export const colorBrandPink800 = "#bc0057";
export const colorBrandPink900 = "#970051";
export const colorBrandPinkContrast50 = "#061a38";
export const colorBrandPinkContrast100 = "#061a38";
export const colorBrandPinkContrast200 = "#061a38";
export const colorBrandPinkContrast300 = "#061a38";
export const colorBrandPinkContrast400 = "#ffffff";
export const colorBrandPinkContrast500 = "#ffffff";
export const colorBrandPinkContrast600 = "#ffffff";
export const colorBrandPinkContrast700 = "#ffffff";
export const colorBrandPinkContrast800 = "#ffffff";
export const colorBrandPinkContrast900 = "#ffffff";
export const colorBrandPurple50 = "#f3e4f3";
export const colorBrandPurple100 = "#e1bae1";
export const colorBrandPurple200 = "#ce8dce";
export const colorBrandPurple300 = "#ba5fba";
export const colorBrandPurple400 = "#ab3aac";
export const colorBrandPurple500 = "#9c0d9e";
export const colorBrandPurple600 = "#8e0a99";
export const colorBrandPurple700 = "#7c0392";
export const colorBrandPurple800 = "#6b008a";
export const colorBrandPurple900 = "#4e007d";
export const colorBrandPurpleContrast50 = "#061a38";
export const colorBrandPurpleContrast100 = "#061a38";
export const colorBrandPurpleContrast200 = "#061a38";
export const colorBrandPurpleContrast300 = "#ffffff";
export const colorBrandPurpleContrast400 = "#ffffff";
export const colorBrandPurpleContrast500 = "#ffffff";
export const colorBrandPurpleContrast600 = "#ffffff";
export const colorBrandPurpleContrast700 = "#ffffff";
export const colorBrandPurpleContrast800 = "#ffffff";
export const colorBrandPurpleContrast900 = "#ffffff";
export const colorBrandRed50 = "#ffeaed";
export const colorBrandRed100 = "#ffcbce";
export const colorBrandRed200 = "#f9a9ab";
export const colorBrandRed300 = "#f46a66";
export const colorBrandRed400 = "#ff443c";
export const colorBrandRed500 = "#ff2d17";
export const colorBrandRed600 = "#f51d1a";
export const colorBrandRed700 = "#e30613";
export const colorBrandRed800 = "#d6000b";
export const colorBrandRed900 = "#c90000";
export const colorBrandRedContrast50 = "#061a38";
export const colorBrandRedContrast100 = "#061a38";
export const colorBrandRedContrast200 = "#061a38";
export const colorBrandRedContrast300 = "#061a38";
export const colorBrandRedContrast400 = "#061a38";
export const colorBrandRedContrast500 = "#ffffff";
export const colorBrandRedContrast600 = "#ffffff";
export const colorBrandRedContrast700 = "#ffffff";
export const colorBrandRedContrast800 = "#ffffff";
export const colorBrandRedContrast900 = "#ffffff";
export const colorBrandGreen50 = "#e6f6e8";
export const colorBrandGreen100 = "#c3e8c6";
export const colorBrandGreen200 = "#9cd9a2";
export const colorBrandGreen300 = "#71cb7c";
export const colorBrandGreen400 = "#4dc05f";
export const colorBrandGreen500 = "#20b441";
export const colorBrandGreen600 = "#13a537";
export const colorBrandGreen700 = "#00932c";
export const colorBrandGreen800 = "#008220";
export const colorBrandGreen900 = "#006307";
export const colorBrandGreenContrast50 = "#061a38";
export const colorBrandGreenContrast100 = "#061a38";
export const colorBrandGreenContrast200 = "#061a38";
export const colorBrandGreenContrast300 = "#061a38";
export const colorBrandGreenContrast400 = "#061a38";
export const colorBrandGreenContrast500 = "#061a38";
export const colorBrandGreenContrast600 = "#ffffff";
export const colorBrandGreenContrast700 = "#ffffff";
export const colorBrandGreenContrast800 = "#ffffff";
export const colorBrandGreenContrast900 = "#ffffff";
export const fontApplicationSHeadline1FontSize = "64px";
export const fontApplicationSHeadline1LineHeight = "72px";
export const fontApplicationSHeadline1LetterSpacing = "-0.5px";
export const fontApplicationSHeadline1TextTransform = "uppercase";
export const fontApplicationSHeadline2FontSize = "48px";
export const fontApplicationSHeadline2LineHeight = "60px";
export const fontApplicationSHeadline2LetterSpacing = "0px";
export const fontApplicationSHeadline2TextTransform = "uppercase";
export const fontApplicationSHeadline3FontSize = "34px";
export const fontApplicationSHeadline3LineHeight = "44px";
export const fontApplicationSHeadline3LetterSpacing = "0.1px";
export const fontApplicationSHeadline3TextTransform = "uppercase";
export const fontApplicationSHeadline4FontSize = "24px";
export const fontApplicationSHeadline4LineHeight = "36px";
export const fontApplicationSHeadline4LetterSpacing = "0.15px";
export const fontApplicationSHeadline4TextTransform = "none";
export const fontApplicationSHeadline5FontSize = "20px";
export const fontApplicationSHeadline5LineHeight = "28px";
export const fontApplicationSHeadline5LetterSpacing = "0.25px";
export const fontApplicationSHeadline5TextTransform = "none";
export const fontApplicationSHeadline6FontSize = "18px";
export const fontApplicationSHeadline6LineHeight = "24px";
export const fontApplicationSHeadline6LetterSpacing = "0.4px";
export const fontApplicationSHeadline6TextTransform = "none";
export const fontApplicationSSubtitle1FontSize = "16px";
export const fontApplicationSSubtitle1LineHeight = "28px";
export const fontApplicationSSubtitle1LetterSpacing = "0.25px";
export const fontApplicationSSubtitle1TextTransform = "none";
export const fontApplicationSSubtitle2FontSize = "14px";
export const fontApplicationSSubtitle2LineHeight = "24px";
export const fontApplicationSSubtitle2LetterSpacing = "0.15px";
export const fontApplicationSSubtitle2TextTransform = "none";
export const fontApplicationSBody1FontSize = "16px";
export const fontApplicationSBody1LineHeight = "24px";
export const fontApplicationSBody1LetterSpacing = "0.5px";
export const fontApplicationSBody1TextTransform = "none";
export const fontApplicationSBody2FontSize = "14px";
export const fontApplicationSBody2LineHeight = "21px";
export const fontApplicationSBody2LetterSpacing = "0.4px";
export const fontApplicationSBody2TextTransform = "none";
export const fontApplicationSButtonFontSize = "16px";
export const fontApplicationSButtonLineHeight = "21px";
export const fontApplicationSButtonLetterSpacing = "1.25px";
export const fontApplicationSButtonTextTransform = "uppercase";
export const fontApplicationSCaptionFontSize = "12px";
export const fontApplicationSCaptionLineHeight = "21px";
export const fontApplicationSCaptionLetterSpacing = "0.4px";
export const fontApplicationSCaptionTextTransform = "none";
export const fontApplicationSOverlineFontSize = "12px";
export const fontApplicationSOverlineLineHeight = "21px";
export const fontApplicationSOverlineLetterSpacing = "1.5px";
export const fontApplicationSOverlineTextTransform = "uppercase";
export const fontApplicationSOverlineFontWeight = "700";
export const fontApplicationSOverlineColor = "#fd90b1";
export const fontApplicationLHeadline1FontSize = "80px";
export const fontApplicationLHeadline1LineHeight = "93px";
export const fontApplicationLHeadline1LetterSpacing = "-1px";
export const fontApplicationLHeadline1TextTransform = "uppercase";
export const fontApplicationLHeadline2FontSize = "64px";
export const fontApplicationLHeadline2LineHeight = "72px";
export const fontApplicationLHeadline2LetterSpacing = "-0.5px";
export const fontApplicationLHeadline2TextTransform = "uppercase";
export const fontApplicationLHeadline3FontSize = "48px";
export const fontApplicationLHeadline3LineHeight = "60px";
export const fontApplicationLHeadline3LetterSpacing = "0px";
export const fontApplicationLHeadline3TextTransform = "uppercase";
export const fontApplicationLHeadline4FontSize = "34px";
export const fontApplicationLHeadline4LineHeight = "44px";
export const fontApplicationLHeadline4LetterSpacing = "0.1px";
export const fontApplicationLHeadline4TextTransform = "none";
export const fontApplicationLHeadline5FontSize = "24px";
export const fontApplicationLHeadline5LineHeight = "36px";
export const fontApplicationLHeadline5LetterSpacing = "0.15px";
export const fontApplicationLHeadline5TextTransform = "none";
export const fontApplicationLHeadline6FontSize = "20px";
export const fontApplicationLHeadline6LineHeight = "28px";
export const fontApplicationLHeadline6LetterSpacing = "0.25px";
export const fontApplicationLHeadline6TextTransform = "none";
export const fontApplicationLSubtitle1FontSize = "18px";
export const fontApplicationLSubtitle1LineHeight = "36px";
export const fontApplicationLSubtitle1LetterSpacing = "0.15px";
export const fontApplicationLSubtitle1TextTransform = "none";
export const fontApplicationLSubtitle2FontSize = "16px";
export const fontApplicationLSubtitle2LineHeight = "28px";
export const fontApplicationLSubtitle2LetterSpacing = "0.1px";
export const fontApplicationLSubtitle2TextTransform = "none";
export const fontApplicationLBody1FontSize = "18px";
export const fontApplicationLBody1LineHeight = "28px";
export const fontApplicationLBody1LetterSpacing = "0.5px";
export const fontApplicationLBody1TextTransform = "none";
export const fontApplicationLBody2FontSize = "16px";
export const fontApplicationLBody2LineHeight = "24px";
export const fontApplicationLBody2LetterSpacing = "0.25px";
export const fontApplicationLBody2TextTransform = "none";
export const fontApplicationLButtonFontSize = "16px";
export const fontApplicationLButtonLineHeight = "21px";
export const fontApplicationLButtonLetterSpacing = "1.25px";
export const fontApplicationLButtonTextTransform = "uppercase";
export const fontApplicationLCaptionFontSize = "12px";
export const fontApplicationLCaptionLineHeight = "21px";
export const fontApplicationLCaptionLetterSpacing = "0.4px";
export const fontApplicationLCaptionTextTransform = "none";
export const fontApplicationLOverlineFontSize = "12px";
export const fontApplicationLOverlineLineHeight = "21px";
export const fontApplicationLOverlineLetterSpacing = "1.5px";
export const fontApplicationLOverlineTextTransform = "uppercase";
export const fontApplicationLOverlineFontWeight = "700";
export const fontApplicationLOverlineColor = "#fd90b1";
export const fontFamilyBrand = "'Source Sans Pro'"; // The brand font family for every content that is not code.
export const fontFamilyMonospace = "'Source Code Pro'"; // The monospace font family that has to be used when displaying code .
export const fontWeightLight = "300"; // The light weight of the font.
export const fontWeightRegular = "400"; // The regular weight of the font.
export const fontWeightBold = "700"; // The bold weight of the font.
export const fontWeightBlack = "900"; // The extra bold weight of the font.
export const layoutApplicationWideXsScreenMinWidth = "0px";
export const layoutApplicationWideXsGutterSize = "16px";
export const layoutApplicationWideXsColumnAmount = "4";
export const layoutApplicationWideXsBodyMaxSize = "90%";
export const layoutApplicationWideXsTypographyScale = "s";
export const layoutApplicationWideXsSpacingScale = "xs";
export const layoutApplicationWideSScreenMinWidth = "600px";
export const layoutApplicationWideSGutterSize = "16px";
export const layoutApplicationWideSColumnAmount = "8";
export const layoutApplicationWideSBodyMaxSize = "90%";
export const layoutApplicationWideSTypographyScale = "s";
export const layoutApplicationWideSSpacingScale = "s";
export const layoutApplicationWideMScreenMinWidth = "905px";
export const layoutApplicationWideMGutterSize = "16px";
export const layoutApplicationWideMColumnAmount = "12";
export const layoutApplicationWideMBodyMaxSize = "86%";
export const layoutApplicationWideMTypographyScale = "l";
export const layoutApplicationWideMSpacingScale = "m";
export const layoutApplicationWideLScreenMinWidth = "1240px";
export const layoutApplicationWideLGutterSize = "24px";
export const layoutApplicationWideLColumnAmount = "12";
export const layoutApplicationWideLBodyMaxSize = "86%";
export const layoutApplicationWideLTypographyScale = "l";
export const layoutApplicationWideLSpacingScale = "l";
export const layoutApplicationWideXlScreenMinWidth = "1440px";
export const layoutApplicationWideXlGutterSize = "24px";
export const layoutApplicationWideXlColumnAmount = "12";
export const layoutApplicationWideXlBodyMaxSize = "86%";
export const layoutApplicationWideXlTypographyScale = "l";
export const layoutApplicationWideXlSpacingScale = "xl";
export const layoutApplicationCompactXsScreenMinWidth = "0px";
export const layoutApplicationCompactXsGutterSize = "16px";
export const layoutApplicationCompactXsColumnAmount = "4";
export const layoutApplicationCompactXsMarginSize = "16px";
export const layoutApplicationCompactXsTypographyScale = "s";
export const layoutApplicationCompactXsSpacingScale = "xs";
export const layoutApplicationCompactSScreenMinWidth = "600px";
export const layoutApplicationCompactSGutterSize = "16px";
export const layoutApplicationCompactSColumnAmount = "8";
export const layoutApplicationCompactSMarginSize = "32px";
export const layoutApplicationCompactSTypographyScale = "s";
export const layoutApplicationCompactSSpacingScale = "s";
export const layoutApplicationCompactMScreenMinWidth = "905px";
export const layoutApplicationCompactMGutterSize = "16px";
export const layoutApplicationCompactMColumnAmount = "12";
export const layoutApplicationCompactMBodyMaxSize = "840px";
export const layoutApplicationCompactMTypographyScale = "l";
export const layoutApplicationCompactMSpacingScale = "m";
export const layoutApplicationCompactLScreenMinWidth = "1240px";
export const layoutApplicationCompactLGutterSize = "24px";
export const layoutApplicationCompactLColumnAmount = "12";
export const layoutApplicationCompactLMarginSize = "192px";
export const layoutApplicationCompactLTypographyScale = "l";
export const layoutApplicationCompactLSpacingScale = "l";
export const layoutApplicationCompactXlScreenMinWidth = "1440px";
export const layoutApplicationCompactXlGutterSize = "24px";
export const layoutApplicationCompactXlColumnAmount = "12";
export const layoutApplicationCompactXlBodyMaxSize = "1040px";
export const layoutApplicationCompactXlTypographyScale = "l";
export const layoutApplicationCompactXlSpacingScale = "xl";
export const layoutColumn1x = "4"; // The least amount of columns in a layout. Used for phone screen sizes.
export const layoutColumn2x = "8"; // The amount of columns used for tablet screen sizes.
export const layoutColumn3x = "12"; // The most amount of columns in a layout. Used for laptop or desktop screen sizes.
export const opacityApplicationIconHigh = 1; // The opacity value for icons with a high emphasis.
export const opacityApplicationIconMedium = 0.6; // The opacity value for icons with a medium emphasis.
export const opacityApplicationIconLow = 0.38; // The opacity value for inactive or disabled icons.
export const opacityApplicationIconContrastHigh = 1; // The opacity value for icons with a high emphasis on a colored or dark background.
export const opacityApplicationIconContrastMedium = 0.74; // The opacity value for icons with a medium emphasis on a colored or dark background.
export const opacityApplicationIconContrastLow = 0.38; // The opacity value for inactive or disabled icons on a colored or dark background.
export const opacityApplicationIconConstrastHigh = 1; // The opacity value for icons with a high emphasis on a colored or light background.
export const opacityApplicationIconConstrastMedium = 0.74; // The opacity value for icons with a medium emphasis on a colored or light background.
export const opacityApplicationIconConstrastLow = 0.38; // The opacity value for inactive or disabled icons on a colored or light background.
export const opacityApplicationTextHigh = 0.87; // The opacity value for normal text or helper text with a high emphasis.
export const opacityApplicationTextMedium = 0.6; // The opacity value for medium emphasis text or helper text.
export const opacityApplicationTextLow = 0.38; // The opacity value for disabled text.
export const opacityApplicationTextContrastHigh = 1; // The opacity value for error text or normal text on a colored or dark background.
export const opacityApplicationTextContrastMedium = 0.74; // The opacity value for medium emphasis text on a colored or dark background.
export const opacityApplicationTextContrastLow = 0.38; // The opacity value for disabled text on a colored or dark background.
export const opacityApplicationTextConstrastHigh = 1; // The opacity value for error text or normal text on a colored or light background.
export const opacityApplicationTextConstrastMedium = 0.74; // The opacity value for medium emphasis text on a colored or light background.
export const opacityApplicationTextConstrastLow = 0.38; // The opacity value for disabled text on a colored or light background.
export const opacityApplicationSurfaceHigh = 1; // The opacity value for surfaces with a high emphasis.
export const opacityApplicationSurfaceMedium = 0.74; // The opacity value for surfaces with a medium emphasis.
export const opacityApplicationSurfaceLow = 0.38; // The opacity value for surfaces that should appear disabled or inactive.
export const opacityBrand1 = 0.38;
export const opacityBrand2 = 0.6;
export const opacityBrand3 = 0.74;
export const opacityBrand4 = 0.87;
export const opacityBrand5 = 1;
export const sizeApplicationSpacingXs3xs = "4px";
export const sizeApplicationSpacingXsXxs = "8px";
export const sizeApplicationSpacingXsXs = "16px";
export const sizeApplicationSpacingXsS = "24px";
export const sizeApplicationSpacingXsM = "32px";
export const sizeApplicationSpacingXsL = "48px";
export const sizeApplicationSpacingXsXl = "64px";
export const sizeApplicationSpacingXsXxl = "80px";
export const sizeApplicationSpacingXs3xl = "88px";
export const sizeApplicationSpacingS3xs = "4px";
export const sizeApplicationSpacingSXxs = "8px";
export const sizeApplicationSpacingSXs = "16px";
export const sizeApplicationSpacingSS = "24px";
export const sizeApplicationSpacingSM = "32px";
export const sizeApplicationSpacingSL = "48px";
export const sizeApplicationSpacingSXl = "64px";
export const sizeApplicationSpacingSXxl = "80px";
export const sizeApplicationSpacingS3xl = "88px";
export const sizeApplicationSpacingM3xs = "4px";
export const sizeApplicationSpacingMXxs = "8px";
export const sizeApplicationSpacingMXs = "24px";
export const sizeApplicationSpacingMS = "32px";
export const sizeApplicationSpacingMM = "48px";
export const sizeApplicationSpacingML = "64px";
export const sizeApplicationSpacingMXl = "80px";
export const sizeApplicationSpacingMXxl = "88px";
export const sizeApplicationSpacingM3xl = "128px";
export const sizeApplicationSpacingL3xs = "4px";
export const sizeApplicationSpacingLXxs = "8px";
export const sizeApplicationSpacingLXs = "24px";
export const sizeApplicationSpacingLS = "32px";
export const sizeApplicationSpacingLM = "48px";
export const sizeApplicationSpacingLL = "64px";
export const sizeApplicationSpacingLXl = "80px";
export const sizeApplicationSpacingLXxl = "88px";
export const sizeApplicationSpacingL3xl = "128px";
export const sizeApplicationSpacingXl3xs = "4px";
export const sizeApplicationSpacingXlXxs = "8px";
export const sizeApplicationSpacingXlXs = "24px";
export const sizeApplicationSpacingXlS = "32px";
export const sizeApplicationSpacingXlM = "48px";
export const sizeApplicationSpacingXlL = "72px";
export const sizeApplicationSpacingXlXl = "88px";
export const sizeApplicationSpacingXlXxl = "96px";
export const sizeApplicationSpacingXl3xl = "192px";
export const sizeFont3xs = "12px";
export const sizeFontXxs = "14px";
export const sizeFontXs = "16px";
export const sizeFontS = "18px";
export const sizeFontM = "20px";
export const sizeFontL = "24px";
export const sizeFontXl = "34px";
export const sizeFontXxl = "48px";
export const sizeFont3xl = "64px";
export const sizeFont4xl = "80px";
export const sizeGutterS = "16px"; // The smallest gutter size in a layout. Used in layouts for small and medium screen sizes.
export const sizeGutterM = "24px"; // The medium gutter size in a layout. Used in layouts for large screen sizes.
export const sizeGutterL = "32px"; // The largest gutter size in a layout. Used in layouts for large screens with emphasis on content and information.
export const sizeLetterSpacing3xs = "-1px"; // The smallest size of the font spacing.
export const sizeLetterSpacingXxs = "-0.5px"; // The second smallest size of the font spacing.
export const sizeLetterSpacingXs = "0px"; // The extra small size of the font spacing.
export const sizeLetterSpacingS = "0.1px"; // The small size of the font spacing.
export const sizeLetterSpacingM = "0.15px"; // The medium size of the font spacing.
export const sizeLetterSpacingL = "0.25px"; // The large size of the font spacing.
export const sizeLetterSpacingXl = "0.4px"; // The extra large size of the font spacing.
export const sizeLetterSpacingXxl = "0.5px"; // The extra extra large size of the font spacing.
export const sizeLetterSpacing3xl = "1.25px"; // The second most largest size of the font spacing.
export const sizeLetterSpacing4xl = "1.5px"; // The largest size of the font spacing.
export const sizeLineHeight3xs = "16px"; // The smallest size of the line height.
export const sizeLineHeightXxs = "21px"; // The smallest size of the line height.
export const sizeLineHeightXs = "24px"; // The second most smalles size of the line height.
export const sizeLineHeightS = "28px"; // The small size of the line height.
export const sizeLineHeightM = "36px"; // The medium size of the line height.
export const sizeLineHeightL = "44px"; // The large size of the line height.
export const sizeLineHeightXl = "60px"; // The extra large size of the line height.
export const sizeLineHeightXxl = "72px"; // The extra extra large size of the line height.
export const sizeLineHeight3xl = "93px"; // The second most largest size of the line height.
export const sizeScreenXs = "0px"; // The smallest possible screen size. Describing screens for phones and small mobile devices.
export const sizeScreenS = "600px"; // The small screen size. Describing screens for big phones and tables.
export const sizeScreenM = "905px"; // The medium screen size. Describing screens for tablets and very small laptops.
export const sizeScreenL = "1240px"; // The large screen size. Describing screens for laptops.
export const sizeScreenXl = "1440px"; // The largest screen size. Describing big laptops or desktops.
export const sizeShapeRadius = "0px"; // The value indicates the radius of the rounded corners in components.
export const sizeSpaceHalfx = "4px";
export const sizeSpace1x = "8px";
export const sizeSpace2x = "16px";
export const sizeSpace3x = "24px";
export const sizeSpace4x = "32px";
export const sizeSpace6x = "48px";
export const sizeSpace8x = "64px";
export const sizeSpace9x = "72px";
export const sizeSpace10x = "80px";
export const sizeSpace11x = "88px";
export const sizeSpace12x = "96px";
export const sizeSpace16x = "128px";
export const sizeSpace24x = "192px";